pipeline:
  identifier: Build_Krishna_Indium_Simple_Node_App_Harness_Artifact_1705484011152
  name: Build Simple-Node-App-Harness-Artifact
  orgIdentifier: default
  projectIdentifier: poc
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Krishna-Indium/Simple-Node-App-Harness-Artifact
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: doc
                    repo: docskrishna/harness_repo
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
