pipeline:
  identifier: Build_Krishna_Indium_Simple_Node_App_Harness_Artifact_1705660829961
  name: Build Simple-Node-App-Harness-Artifact
  orgIdentifier: default
  projectIdentifier: demo_poc
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Krishna-Indium/Simple-Node-App-Harness-Artifact
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: docker_poc
                    repo: docskrishna/harness_repo
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
