pipeline:
  identifier: Build_Krishna_Indium_Simple_Node_App_Harness_Artifact_1705640545252
  name: Build Simple-Node-App-Harness-Artifact
  orgIdentifier: default
  projectIdentifier: hello_world
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Krishna-Indium/Simple-Node-App-Harness-Artifact
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: docker
                    repo: docskrishna/harness_repo
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: svc
          environment:
            environmentRef: env
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
